apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: order-statestore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: "https://<YOUR_COSMOS_ACCOUNT>.documents.azure.com:443/"
  - name: masterKey
    secretKeyRef:
      name: cosmos-key
      key: cosmos-key
  - name: database
    value: "OrderDatabase"
  - name: collection
    value: "OrderState"