name: Enterprise System CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-order-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get ACR Credentials
        id: acr-creds
        run: |
          USERNAME=$(az acr credential show --name acrchandhiya123 --query "username" -o tsv)
          PASSWORD=$(az acr credential show --name acrchandhiya123 --query "passwords[0].value" -o tsv)
          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Build & Deploy Order Service
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: acrchandhiya123
          acrUsername: ${{ steps.acr-creds.outputs.username }}
          acrPassword: ${{ steps.acr-creds.outputs.password }}
          containerAppName: order-service
          resourceGroup: rg-resumeiq
          containerAppEnvironment: env-resumeiq
          appSourcePath: ${{ github.workspace }}/order_service
          dockerfilePath: Dockerfile

  deploy-invoice-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get ACR Credentials
        id: acr-creds
        run: |
          USERNAME=$(az acr credential show --name acrchandhiya123 --query "username" -o tsv)
          PASSWORD=$(az acr credential show --name acrchandhiya123 --query "passwords[0].value" -o tsv)
          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT

      - name: Build & Deploy Invoice Service
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: acrchandhiya123
          acrUsername: ${{ steps.acr-creds.outputs.username }}
          acrPassword: ${{ steps.acr-creds.outputs.password }}
          containerAppName: invoice-service
          resourceGroup: rg-resumeiq
          containerAppEnvironment: env-resumeiq
          appSourcePath: ${{ github.workspace }}/invoice_service
          dockerfilePath: Dockerfile

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Frontend to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: ""
          output_location: ""
